### ISSUE TITLE
inline syntax

### ISSUE THREAD

**Issue by feitian124** [hysios/ember-cli-ember-validations#1]
block syntax is flexible and easy to custom your own layout:

``` javascript
{{#validate-with propertyBinding="user.login"}}
  <label>
    {{validate-message}}
  </label>
  {{input value=user.login}}
{{/validate-with}}
```

but for simple case, block syntax is too long and redundant, please consider add inline syntax for simple case, like below:

``` javascript
{{validate-with value="user.login"}}
```

**Comment by feitian124** [comment]
and also, if inline syntax is added, it is easy to find that the name `validate-with` is not clear enough, how about change to `input-validate`?

**Comment by hysios** [comment]
@feitian124 `input-validate` syntax is surely clear && simple, but `validate-with` && `validate-message` parameters  is not  going stable, we quickly add `input-validate` shortcuts for `validate-with` with {{input}} after a few days.
